apiVersion: 1

contactPoints:
  - name: Telegram Infra
    receivers:
      - uid: telegram-infra
        type: webhook
        settings:
          url: "http://alert-proxy:5000/webhook"
          httpMethod: POST
        disableResolveMessage: false

policies:
  - receiver: Telegram Infra
    group_by: ["grafana_folder", "alertname"]
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
