data_source batch_data:
  type: postgres
  connection:
    host: ${POSTGRES_HOST}
    port: "5432"
    database: ${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    schema: public
