global:
  scrape_interval: 15s

scrape_configs:
  - job_name: cadvisor
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: postgres-batch
    metrics_path: /metrics
    static_configs:
      - targets: ["postgres-exporter-batch:9187"]

  - job_name: postgres-stream
    metrics_path: /metrics
    static_configs:
      - targets: ["postgres-exporter-stream:9187"]

  - job_name: kafka
    static_configs:
      - targets: ["kafka-exporter:9308"]

  - job_name: inference-ml
    metrics_path: /metrics
    static_configs:
      - targets: ["inference-ml:8000"]

  - job_name: soda-exporter
    metrics_path: /metrics
    static_configs:
      - targets: ["soda-exporter:8000"]
