{
 "title": "Data Quality Monitoring",
 "templating": {
  "list": [
   {
    "name": "source",
    "label": "Source",
    "query": "label_values(soda_check_result{check_name!=\"unknown\"}, data_source)"
   },
   {
    "name": "tbl",
    "label": "Table",
    "query": "label_values(soda_check_result{check_name!=\"unknown\", data_source=~\"$source\"}, table)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "w": 24, "h": 1, "x": 0, "y": 0 } },
  {
   "title": "Total Checks",
   "type": "stat",
   "gridPos": { "w": 12, "h": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(soda_checks_passed) + sum(soda_checks_failed)"
    }
   ]
  },
  {
   "title": "Pass Rate",
   "type": "gauge",
   "gridPos": { "w": 12, "h": 5, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(soda_checks_passed) / (sum(soda_checks_passed) + sum(soda_checks_failed))) * 100",
     "legendFormat": "Pass Rate"
    }
   ]
  },
  { "title": "Check Results", "type": "row", "gridPos": { "w": 24, "h": 1, "x": 0, "y": 6 } },
  {
   "title": "Individual Check Results",
   "type": "table",
   "gridPos": { "w": 24, "h": 10, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "soda_check_result{check_name!=\"unknown\", data_source=~\"${source:regex}\", table=~\"${tbl:regex}\"}"
    }
   ]
  }
 ]
}