apiVersion: 1

datasources:
  - name: Prometheus Stream
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: true

  - name: Prometheus Batch
    type: prometheus
    url: http://${BATCH_TAILSCALE_IP}:9090
    access: proxy
